Repository VathsalaAchar/MLA-pilot-group4, pull requests merged in 2024-04, with the labels that each got.

#31 User profile schema api
  activity-tracking/models/userprofile.model.js
  activity-tracking/package-lock.json
  activity-tracking/populatedb.js
  activity-tracking/readme.md
  activity-tracking/routes/userprofiles.js
  activity-tracking/server.js
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/navbar.js
  frontend/src/components/userProfile.css
  frontend/src/components/userProfile.js
  nginx/default.conf
Labels: enhancement

#32 User profile endpoint tests
  activity-tracking/routes/userprofiles.js
  activity-tracking/test/exercise.test.js
  activity-tracking/test/userprofile.test.js
Labels: tests

#30 Added changes for a new exercise type walking
  activity-tracking/models/exercise.model.js
  activity-tracking/models/weeklytarget.model.js
  activity-tracking/routes/weeklytargets.js
  analytics/core/gql_schema.py
  frontend/src/components/journal.js
  frontend/src/components/statistics.js
  frontend/src/components/trackExercise.js
Labels: enhancement

#35 Weekly target fix
  activity-tracking/routes/weeklytargets.js
  activity-tracking/test/weeklytarget.test.js
  frontend/src/components/journal.js
Labels: bug, tests

#34 Updating test to include walking
  .dockerignore
  activity-tracking/populatedb.js
  activity-tracking/test/weeklytarget.test.js
Labels: tests

#12 adding changes for junit and mockito tests
  authservice/src/test/java/com/authservice/auth/AuthserviceApplicationTests.java
Labels: tests
