Repository VathsalaAchar/MLA-pilot-group4, pull requests merged in 2024-02, with the labels that each got.

#1 Database split across services
  activity-tracking/config.json
  activity-tracking/server.js
  analytics/.env
  analytics/app.py
  authservice/src/main/resources/application.properties
  docker-compose.yml
Labels: enhancement

#3 Ngingx setup
  activity-tracking/cypress/e2e/exercise.cy.js
  docker-compose.yml
  frontend/src/api.js
  frontend/src/components/journal.js
  frontend/src/components/login.js
  frontend/src/components/signup.js
  frontend/src/components/statistics.js
  frontend/src/config.js
  nginx/default.conf
Labels: enhancement

#8 placeholder test for pytest
  analytics/test_analytics.py
Labels: bug

#7 Add readme for all services
  activity-tracking/readme.md
  analytics/readme.md
  authservice/readme.md
  frontend/readme.md
Labels: documentation

#11 Implementation of Password strength Criteria
  frontend/src/components/signup.js
Labels: enhancement
