Repository VathsalaAchar/MLA-pilot-group4, pull requests merged in 2024-03, with the labels that each got.

#13 updating gitignore for authservice
  authservice/.gitignore
  authservice/package-lock.json
  authservice/package.json
Labels: codebase improvement

#14 Modularising the analytics app
  analytics/Dockerfile
  analytics/core/__init__.py
  analytics/core/models.py
  analytics/core/views.py
  analytics/run.py
  analytics/tests/test_analytics.py
Labels: codebase improvement

#16 validation for-exercise type
  frontend/src/components/trackExercise.js
Labels: bug

#15 Graphql schema integration
  analytics/core/gql_schema.py
  analytics/core/models.py
  analytics/core/views.py
  analytics/requirements.txt
Labels: enhancement

#19 Manage exercises
  .vscode/launch.json
  activity-tracking/routes/exercises.js
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/api.js
  frontend/src/components/journal.css
  frontend/src/components/manage.js
  frontend/src/components/navbar.js
  frontend/src/components/trackExercise.js
Labels: enhancement

#17 Analytics test setup
  .github/workflows/deploy-Analytics.yml
  analytics/config.py
  analytics/core/__init__.py
  analytics/core/gql_schema.py
  analytics/core/models.py
  analytics/core/views.py
  analytics/run.py
  analytics/tests/__init__.py
  analytics/tests/conftest.py
  analytics/tests/db_init_data.json
  analytics/tests/test_analytics.py
Labels: enhancement

#20 Weekly targets schema api
  activity-tracking/models/weeklytarget.model.js
  activity-tracking/package-lock.json
  activity-tracking/package.json
  activity-tracking/populatedb.js
  activity-tracking/readme.md
  activity-tracking/routes/weeklytargets.js
  activity-tracking/server.js
  frontend/src/components/journal.css
  frontend/src/components/journal.js
  nginx/default.conf
Labels: enhancement

#21 added track distance changes
  activity-tracking/models/exercise.model.js
  activity-tracking/routes/exercises.js
  frontend/src/App.css
  frontend/src/components/trackExercise.js
Labels: enhancement

#22 UI overlook changes
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/journal.css
  frontend/src/components/journal.js
  frontend/src/components/login.js
  frontend/src/components/manage.css
  frontend/src/components/manage.js
  frontend/src/components/navbar.js
  frontend/src/components/signup.js
  frontend/src/components/statistics.css
  frontend/src/components/statistics.js
  frontend/src/components/trackExercise.js
Labels: enhancement

#24 Pace and speed with UI changes
  activity-tracking/models/exercise.model.js
  activity-tracking/routes/exercises.js
  analytics/core/gql_schema.py
  analytics/core/views.py
  frontend/src/App.css
  frontend/src/components/manage.js
  frontend/src/components/statistics.css
  frontend/src/components/statistics.js
  frontend/src/components/trackExercise.css
  frontend/src/components/trackExercise.js
Labels: enhancement

#23 Graphql schema update for filtering user
  analytics/core/gql_schema.py
  analytics/core/query.py
  analytics/core/views.py
  analytics/readme.md
  analytics/tests/test_analytics.py
  frontend/src/components/statistics.js
Labels: enhancement

#25 Activity tracking tests for endpoints
  .github/workflows/deploy-ActivityTracking.yml
  activity-tracking/package-lock.json
  activity-tracking/package.json
  activity-tracking/routes/exercises.js
  activity-tracking/routes/weeklytargets.js
  activity-tracking/server.js
  activity-tracking/test/exercise.test.js
  activity-tracking/test/weeklytarget.test.js
Labels: enhancement, tests

#26 Fix for failing tests on activity tracking
  activity-tracking/models/exercise.model.js
  activity-tracking/test/exercise.test.js
Labels: bug

#27 GraphQL schema for exercises aggregated by week
  analytics/core/gql_schema.py
  analytics/core/query.py
  analytics/core/views.py
  analytics/tests/db_init_data.json
  analytics/tests/test_analytics.py
  frontend/src/components/journal.js
  frontend/src/components/statistics.js
Labels: enhancement
